import { FakeCallScenario } from './types';

export const fakeCallScenarios: FakeCallScenario[] = [
    {
        id: 'pickup-outside',
        title: 'Friend picking you up outside',
        description: 'Caller helps the user leave and stay on the phone.',
        transcript: [
            { speaker: 'caller', text: 'Hey, where are you right now?' },
            { speaker: 'user', text: 'I’m still here.' },
            {
                speaker: 'caller',
                text: 'Still there? I thought you were leaving already. I’m basically outside.',
            },
            { speaker: 'user', text: 'Wait, you’re here already?' },
            {
                speaker: 'caller',
                text: 'Yeah, I texted you a minute ago. I’m near the front. Where are you, exactly?',
            },
            { speaker: 'user', text: 'I’m walking over now.' },
            {
                speaker: 'caller',
                text: 'Okay, good. Just come toward the main entrance. Don’t go around the side. I’m staying on with you.',
            },
            { speaker: 'user', text: 'Okay.' },
            { speaker: 'caller', text: 'Do you have all your stuff with you?' },
            { speaker: 'user', text: 'Yeah, I think so.' },
            {
                speaker: 'caller',
                text: 'Check really quick. Phone, keys, bag. I don’t want you going back in again once you’re out.',
            },
            { speaker: 'user', text: 'Yeah, I have everything.' },
            { speaker: 'caller', text: 'Good. Is it crowded where you are, or no?' },
            { speaker: 'user', text: 'A little, not really, kind of.' },
            {
                speaker: 'caller',
                text: 'Alright. Just stay where other people are while you walk over. I’m looking for your jacket right now. What are you wearing again?',
            },
            { speaker: 'user', text: 'I’m wearing [describes clothing].' },
            {
                speaker: 'caller',
                text: 'Okay, got it. I’m by the curb, near the corner, by the front doors. Walk straight there. Don’t worry, I see the entrance.',
            },
            { speaker: 'user', text: 'Okay, I’m coming.' },
            {
                speaker: 'caller',
                text: 'Take your time, but don’t stop for anybody. If someone talks to you, just keep walking and stay on with me.',
            },
            { speaker: 'user', text: 'Okay.' },
            { speaker: 'caller', text: 'Are you almost at the door?' },
            { speaker: 'user', text: 'Yeah.' },
            { speaker: 'caller', text: 'Good. Once you’re outside, tell me what you see.' },
            {
                speaker: 'user',
                text: 'I see the street, cars, the corner, the front steps.',
            },
            {
                speaker: 'caller',
                text: 'Perfect. I’m going to pull a little closer. Stay where it’s bright. Do you see me yet?',
            },
            { speaker: 'user', text: 'Not yet.' },
            { speaker: 'caller', text: 'That’s fine. Keep talking to me. I’m right here. You’re okay.' },
            { speaker: 'user', text: 'Okay.' },
            {
                speaker: 'caller',
                text: 'Do you want to tell me what happened, or do you just want to get out first?',
            },
            { speaker: 'user', text: 'Let’s just get out first.' },
            {
                speaker: 'caller',
                text: 'Yeah, that’s fine. We can talk after. Just keep walking toward the front.',
            },
        ],
    },
    {
        id: 'walking-home-check-in',
        title: 'Walking home check-in',
        description: 'Caller stays on the phone while the user walks back at night.',
        transcript: [
            { speaker: 'caller', text: 'Hey, are you heading back yet?' },
            { speaker: 'user', text: 'Not yet.' },
            {
                speaker: 'caller',
                text: 'Okay. I just wanted to check because it’s getting late, and I’d rather you not walk back alone.',
            },
            { speaker: 'user', text: 'Yeah, I’m about to leave.' },
            { speaker: 'caller', text: 'Good. Call me while you’re walking.' },
            { speaker: 'user', text: 'I’m on with you now.' },
            { speaker: 'caller', text: 'Perfect. Just stay on. Where are you walking from?' },
            { speaker: 'user', text: '[Answers.]' },
            {
                speaker: 'caller',
                text: 'Okay, that’s fine. Take the more populated route, not the shortcut. Are there people around you?',
            },
            { speaker: 'user', text: 'Yes, kind of, not many.' },
            {
                speaker: 'caller',
                text: 'Alright. Keep to the better-lit side. You don’t need to rush, just keep moving.',
            },
            { speaker: 'user', text: 'Okay.' },
            { speaker: 'caller', text: 'Did you bring a jacket? It sounds cold out.' },
            { speaker: 'user', text: 'Yeah, I have it.' },
            {
                speaker: 'caller',
                text: 'Good. And you have your keys ready, right? I don’t want you standing outside your place looking through your bag.',
            },
            { speaker: 'user', text: 'Let me check… yeah, I have them.' },
            { speaker: 'caller', text: 'Okay, great. Just keep talking to me. What street are you on now?' },
            { speaker: 'user', text: '[Answers.]' },
            {
                speaker: 'caller',
                text: 'Alright, I know where that is. You’re fine. Once you get to the next corner, tell me if it’s quieter over there.',
            },
            { speaker: 'user', text: 'Okay.' },
            {
                speaker: 'caller',
                text: 'Also, sorry if I sound annoying — I’m just making sure you get back okay.',
            },
            { speaker: 'user', text: 'No, it’s okay.' },
            {
                speaker: 'caller',
                text: 'Good. Honestly, I’d rather be annoying than have you walk back by yourself in silence.',
            },
            { speaker: 'user', text: 'Fair.' },
            {
                speaker: 'caller',
                text: 'Do you want me to keep distracting you? I can just talk about random stuff.',
            },
            { speaker: 'user', text: 'Yeah, keep talking.' },
            {
                speaker: 'caller',
                text: 'Okay. So anyway, I was going to tell you earlier — [shifts into ordinary conversation]. Did you end up eating anything there? How was it? Who did you go with? Was it crowded?',
            },
            { speaker: 'user', text: '[Answers.]' },
            { speaker: 'caller', text: 'Yeah, that sounds about right. Are you getting closer now?' },
            { speaker: 'user', text: 'A little.' },
            {
                speaker: 'caller',
                text: 'Okay, good. Stay on the main road. Once you’re closer, I’ll buzz you in, I’ll meet you downstairs, I’ll turn the porch light on.',
            },
            { speaker: 'user', text: 'Okay.' },
            {
                speaker: 'caller',
                text: 'And if you want, don’t hang up when you get inside. Stay on until your door’s locked.',
            },
        ],
    },
    {
        id: 'leave-now-check-in',
        title: 'Urgent leave-now check-in',
        description: 'Caller urges the user to leave immediately and stay near people.',
        transcript: [
            { speaker: 'caller', text: 'Hey. Why haven’t you been answering?' },
            { speaker: 'user', text: 'Sorry, I’m out right now.' },
            { speaker: 'caller', text: 'Okay, where?' },
            { speaker: 'user', text: 'Still near [location].' },
            { speaker: 'caller', text: 'Alright. I need you to leave now.' },
            { speaker: 'user', text: 'Okay.' },
            {
                speaker: 'caller',
                text: 'No, I’m serious. Don’t stay there longer than you have to. Go somewhere brighter and closer to people.',
            },
            { speaker: 'user', text: 'I’m moving now.' },
            { speaker: 'caller', text: 'Good. Keep talking to me while you walk.' },
            { speaker: 'user', text: 'Okay.' },
            { speaker: 'caller', text: 'Do you have everything with you?' },
            { speaker: 'user', text: 'Yeah.' },
            {
                speaker: 'caller',
                text: 'And don’t look down at your phone too much. Just keep me on speaker or hold it normally and keep walking.',
            },
            { speaker: 'user', text: 'Okay.' },
            { speaker: 'caller', text: 'Are you by yourself?' },
            { speaker: 'user', text: 'Yeah, mostly, kind of.' },
            {
                speaker: 'caller',
                text: 'Alright. Head toward the main street. I’d rather you be somewhere visible.',
            },
            { speaker: 'user', text: 'Okay.' },
            {
                speaker: 'caller',
                text: 'I’m not trying to scare you. I just want you somewhere safer while we figure out where you’re going next.',
            },
            { speaker: 'user', text: 'I know.' },
            {
                speaker: 'caller',
                text: 'Good. Are you going straight home, or do you want me to come get you?',
            },
            { speaker: 'user', text: 'I can go home, come get me, I’m not sure.' },
            {
                speaker: 'caller',
                text: 'If you’re not sure, then stay where people are and I’ll come get you. Don’t stand off to the side somewhere by yourself.',
            },
            { speaker: 'user', text: 'Okay.' },
            { speaker: 'caller', text: 'Tell me what’s around you right now.' },
            { speaker: 'user', text: '[Answers.]' },
            {
                speaker: 'caller',
                text: 'Good. Stay there for a second. I’m putting my shoes on, grabbing my keys, heading out now.',
            },
            { speaker: 'user', text: 'Okay.' },
            {
                speaker: 'caller',
                text: 'And listen — if anyone tries to stop you or talk to you, keep walking and keep talking to me. Don’t worry about being polite.',
            },
            { speaker: 'user', text: 'Okay.' },
            {
                speaker: 'caller',
                text: 'Good. I’m with you. Just keep moving. Are you near the corner yet?',
            },
            { speaker: 'user', text: 'Almost.' },
            {
                speaker: 'caller',
                text: 'Alright. When you get there, turn toward the busier side. I’ll stay on until I know exactly where you are.',
            },
            { speaker: 'user', text: 'Okay.' },
            { speaker: 'caller', text: 'You’re doing fine. Just keep going.' },
        ],
    },
    {
        id: 'casual-walking-bored',
        title: 'Casual walking check-in',
        description: 'A light, casual call to avoid walking alone in silence.',
        transcript: [
            { speaker: 'caller', text: 'Hey, can you stay on for a second? I’m walking and I’m bored.' },
            { speaker: 'user', text: 'Yeah, okay.' },
            { speaker: 'caller', text: 'Thank you. I didn’t feel like walking in silence.' },
            { speaker: 'user', text: 'Where are you?' },
            { speaker: 'caller', text: 'I’m almost back, I’m outside, I’m heading over now. Where are you?' },
            { speaker: 'user', text: 'Still here.' },
            { speaker: 'caller', text: 'Okay. Are you leaving soon?' },
            { speaker: 'user', text: 'Yeah, probably now.' },
            {
                speaker: 'caller',
                text: 'Good, then we can just stay on together. Did you bring your jacket? It’s colder than I thought.',
            },
            { speaker: 'user', text: 'Yeah.' },
            {
                speaker: 'caller',
                text: 'Good. I feel like every single time one of us goes out, we forget something.',
            },
            { speaker: 'user', text: 'Literally.' },
            { speaker: 'caller', text: 'Do you have your keys though? Actually check.' },
            { speaker: 'user', text: 'Yeah, I do.' },
            { speaker: 'caller', text: 'Okay, nice. Just keep talking to me while you head out.' },
        ],
    }
];